### ISSUE TITLE
AizuSpider改造計画

### ISSUE THREAD

**Issue by shimoe** [WRS-TNK/choreonoid#1]
AizuSpiderのモデルで改造する(すべき)ところで

現在出来ていること
・左腕のモデル追加
・VLP-16の取付

これからやるところ
・ハンドカメラ追加
・体重増加？

**Comment by RyodoTanaka** [comment]
@shimoe 
ありがとう！
進捗あれば（詰まっとるの含む）SlackでもこのIssueでも良いのでよろしく！

**Comment by shimoe** [comment]
いろいろ漁ってたらベロダインもLRF元からついてました・・・
ジャイロとかいろいろ付いているんですがセンサ情報のパブリッシュができない・・・

**Comment by RyodoTanaka** [comment]
oh
ついとるのは知っとるんかと思いよった
申し訳ない

でもPublishできないのね...
こまったな

**Comment by shimoe** [comment]
choreonoid_ros_pkgによるLRFやjoint_stateのパブリっシュ確認しました

問題点として
・AGXシミュレータとの共存ができてない
・rviz上での確認は取れてない(urdfがないから？)

がいまのとこ挙げられます

**Comment by RyodoTanaka** [comment]
ありがとう
> Rviz上で確認は取れてない

これは，Topicの中身が入っているならRvizのFixed Frameの問題なので，大丈夫．
URDFというよりは，TF出てればいろいろ一度に見ることはできる．

それよりも，
> AGXシミュレータとの共存ができてない

これが圧倒的にやばい
共存できないというのは具体的に何が問題で起きるん？

**Comment by shimoe** [comment]
原因は目下不明
LRFなどのシミュレーションはAISTシミュ管轄のGLビジョンシミュレータが担当しているのですが
AGXシミュで動くモデルを使ってGLシミュをさせようとするとフリーズする・・・というより今回の場合AizuSpiderが虚空に消え，世界がモノクロになり，シミュレーションの時間経過は停止するとかいう状況です．

やったこととしてはAGX用のサンプルプロジェクト(/sample/WRS2018/AizuSpider_SA.cnoid)にAISTシミュアイテム(GLシミュアイテム)を追加，その後AISTシミュ(GLシミュ)を実行しました
プロジェクトファイルの記述をAISTシミュプロジェクトのものと比較してもGLシミュ部分に変わった記述はありません．
AGXシミュ用に何か追記する必要があるかもしれませんがマニュアルにも書かれてないのでこれも不明です．

**Comment by shimoe** [comment]
フリーズする際，AizuSpider本体が消滅する前にクローラのベルトが位置ずれを起こして４つのクローラが逆パカしているところを見ると，やはりAGXプラグインとの関係でフリーズしていると思います

**Comment by RyodoTanaka** [comment]
なるほど...
これはかなり緊急性の高い修正が必要やな
完全な憶測やけど，GLシミュとAGXシミュが同時に同じメモリを参照したりしてしまっとるのかもしれん．．．
これはご本人案件やな
早急にChoreonoid Discuss にIssue立ててクレイ！！！
ROS Pluginを作ったほうが早いのか，この問題を修正するほうが早いのか聞いてきます．

**Comment by RyodoTanaka** [comment]
おそらくやけど，AGXが参照しているリンカのバージョンがずれてて起きてるかも
とのこと
具体的には，シンボリックリンクの名前は一緒なのにバージョンが違うくて起きてるかもしれない
で，対処法なんやけど，今んとこない
いずれにせよ
具体的にどこで落ちてるのか何が原因なのかを調べるために
センサプラグインとか全部コメントアウトしたモデルを起動して
AGXとbridgeを起動してみて欲しい
またその際に，予めDebugモードでビルドしておいてcoreファイルが生成されるようにしておいてほしい
最終的に，どの関数で落ちてるのかを調べる必要がある

**Comment by shimoe** [comment]
デバッグモードでのビルドはcmakeオプションに-DEBUG ONとかすればいいかんじですかね？

**Comment by shimoe** [comment]
よく見たら初期設定の時に```-DMAKE_BUILD_TYPE=Debug```ってあるので最初からデバッグモードっぽいですね

**Comment by RyodoTanaka** [comment]
@shimoe 
遅くなってほんと申し訳ない
中岡さんに言われたのは，
- 落ちる原因はセンサプラグインのせいかもしれない
- 一度すべてのセンサをOFFにして，本体だけ起動してどうなるか調べる
- その後ひとつずつONにしてどのプラグイン周りで落ちてるのか調べる
- 落ちてるプラグインがわかったら，coreファイルからバックトレースしてどの関数で落ちてるか調べる

という，まぁいわゆる普通のデバッグ作業をしてからもう一回聞く必要がある
ということ

**Comment by RyodoTanaka** [comment]
@shimoe 
上記の作業お願いできる？
とりあえずどのあたりで落ちてるのかを知りたい．

**Comment by shimoe** [comment]
やるのは全然構わないんですけど
coreファイルがどんなのとかが分からないので教えて欲しいです。

起動するものとしては
AGX対応Aizuspider本体(センサ無し)
何がしかのワールド
AISTシミュ(GLビジョン)
AGXシミュ
で大丈夫ですかね？

**Comment by RyodoTanaka** [comment]
@shimoe 
coreファイルってのは，CとかC++でコアダンプした時にできるファイル
gdbデバッガを使って解析するときに必要なファイルで，gdbによってbt（バックトレース）すると，落ちてるところのIDとか関数名とかがわかる．
やりかたは
1. デバッグモード（具体的にはコンパイル時に -g オプションと最適化OFFオプション -O0 をつけてコンパイル）でコンパイル
2. `ulimit -c unlimited` コマンドを打つ
3. プログラムを実行（ここでは実行プログラムを a.out と呼ぶ）し，無事コアダンプする．そしてcoreファイルができる．
4. `gdb ./a.out core` でデバッガを起動
5. `bt` コマンドでどこで落ちてたか確認する

というのが使い方．

**Comment by RyodoTanaka** [comment]
起動するものは，書いてくれてるヤツでOK！

**Comment by shimoe** [comment]
了解です
ありがとうございます

取り敢えずやってみます

**Comment by RyodoTanaka** [comment]
だいぶ前&DoubleArmに移行したので閉じます
